issue 120: improve path handling on CLI
* handle multiple input files as arguments
* support Ruby 1.9.3.194

Addressing:

/var/lib/gems/1.9.1/gems/puppet-lint-0.1.13/bin/puppet-lint:89:in `<top (required)>': undefined method `each' for "base.pp":String (NoMethodError)
    from /usr/local/bin/puppet-lint:19:in `load'
    from /usr/local/bin/puppet-lint:19:in `<main>'

This changeset implements the patch described by @ferrylandzaat
in rodjek/puppet-lint#120 and resolves the above traceback as well
as enabling the CLI to handle multiple files as arguments.

Tested-by: Paul Morgan <jumanjiman@gmail.com>
  rake test
  71 examples, 0 failures